b2 = Course.create(title: "IT 1000", professor: "Luis Brown")
b3 = Course.create(title: "ES 2000", professor: "Mary Randal")
b4 = Course.create(title: "MH 3000", professor: "Sierra Swift")
b5 = Course.create(title: "AS 4000", professor: "Dente Cruz")
b6 = Course.create(title: "CP 5000", professor: "Olu Bhal")
b7 = Course.create(title: "LO 6000", professor: "Puran Saed")